# Generated by Django 4.1.6 on 2023-02-03 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="fifa_coode",
            new_name="fifa_code",
        ),
    ]
