# Generated by Django 4.1.6 on 2023-02-03 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_fifa_coode_team_fifa_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="fist_cup",
            new_name="first_cup",
        ),
    ]
